"""
Swarm-Forge Memory System
Implements Epistemic Compounding via LESSON.md, SKILL.md, and
semantic vector retrieval from Milvus Lite.
"""

from __future__ import annotations
import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Optional, Any
from schemas import LessonEntry, ExperienceVector, AgentRole

logger = logging.getLogger(__name__)

MEMORY_DIR = Path(os.environ.get("MEMORY_DIR", "./memory"))
LESSON_FILE = MEMORY_DIR / "LESSON.md"
SKILL_FILE = MEMORY_DIR / "SKILL.md"
EXPERIENCE_FILE = MEMORY_DIR / "experiences.jsonl"


# ── LESSON.md Manager ───────────────────────────────────────────────────────

class LessonManager:
    """
    Writes and reads the LESSON.md episodic failure memory.
    Every bug fix gets abstracted into a generalized heuristic here.
    New agents inherit this wisdom at initialization time.
    """

    def __init__(self):
        MEMORY_DIR.mkdir(parents=True, exist_ok=True)
        if not LESSON_FILE.exists():
            LESSON_FILE.write_text(
                "# Swarm-Forge LESSON.md\n"
                "## Operational Heuristics from Production Failures\n\n"
                "_Auto-generated by Epistemic Compounding engine._\n\n"
            )

    def append_lesson(self, entry: LessonEntry) -> None:
        """Append a new lesson to LESSON.md."""
        section = (
            f"\n### Lesson {entry.lesson_id[:8]} | "
            f"{entry.timestamp.strftime('%Y-%m-%d %H:%M')}\n\n"
            f"**Failure Pattern:** {entry.failure_pattern}\n\n"
            f"**Root Cause:** {entry.root_cause}\n\n"
            f"**Heuristic:** {entry.generalized_heuristic}\n\n"
            f"**Applicable Roles:** "
            f"{', '.join(r.value for r in entry.applicable_agent_roles)}\n\n"
            f"**Domain Tags:** {', '.join(entry.domain_tags)}\n\n"
            f"---\n"
        )
        with open(LESSON_FILE, "a") as f:
            f.write(section)
        logger.info(f"Lesson appended: {entry.lesson_id[:8]}")

    def load_lessons_for_agent(self, role: AgentRole) -> str:
        """
        Returns the relevant LESSON.md sections for a given agent role.
        This is injected into new agent system prompts at spawn time.
        """
        if not LESSON_FILE.exists():
            return ""
        content = LESSON_FILE.read_text()
        lines = content.split("\n")
        relevant_sections = []
        current_section = []
        in_relevant = False

        for line in lines:
            if line.startswith("### Lesson"):
                if in_relevant and current_section:
                    relevant_sections.extend(current_section)
                current_section = [line]
                in_relevant = False
            elif f"**Applicable Roles:**" in line and role.value in line:
                in_relevant = True
                current_section.append(line)
            else:
                current_section.append(line)

        if in_relevant and current_section:
            relevant_sections.extend(current_section)

        if not relevant_sections:
            return ""

        return (
            f"## Inherited Operational Wisdom (LESSON.md)\n\n"
            + "\n".join(relevant_sections)
        )

    def get_full_lesson_context(self) -> str:
        """Returns entire LESSON.md for Opus-level planning."""
        if not LESSON_FILE.exists():
            return "No lessons recorded yet."
        return LESSON_FILE.read_text()


# ── SKILL.md Manager ────────────────────────────────────────────────────────

class SkillManager:
    """
    Manages the SKILL.md reusable pattern library.
    Records successful patterns that worked well across deployments.
    """

    def __init__(self):
        MEMORY_DIR.mkdir(parents=True, exist_ok=True)
        if not SKILL_FILE.exists():
            SKILL_FILE.write_text(
                "# Swarm-Forge SKILL.md\n"
                "## Reusable Patterns from Successful Deployments\n\n"
            )

    def append_skill(
        self,
        skill_name: str,
        description: str,
        code_pattern: str,
        applicable_roles: list[AgentRole],
        tags: list[str]
    ) -> None:
        section = (
            f"\n### Skill: {skill_name}\n\n"
            f"**Description:** {description}\n\n"
            f"**Applicable Roles:** "
            f"{', '.join(r.value for r in applicable_roles)}\n\n"
            f"**Tags:** {', '.join(tags)}\n\n"
            f"```python\n{code_pattern}\n```\n\n---\n"
        )
        with open(SKILL_FILE, "a") as f:
            f.write(section)
        logger.info(f"Skill recorded: {skill_name}")

    def load_skills_for_agent(self, role: AgentRole, tags: list[str] = None) -> str:
        if not SKILL_FILE.exists():
            return ""
        content = SKILL_FILE.read_text()
        if not tags:
            return content
        lines = content.split("\n")
        relevant = []
        current = []
        in_relevant = False
        for line in lines:
            if line.startswith("### Skill:"):
                if in_relevant and current:
                    relevant.extend(current)
                current = [line]
                in_relevant = False
            elif "**Tags:**" in line:
                if any(tag in line for tag in tags):
                    in_relevant = True
                current.append(line)
            else:
                current.append(line)
        if in_relevant and current:
            relevant.extend(current)
        return "\n".join(relevant) if relevant else ""


# ── Experience Library (JSONL + Milvus) ─────────────────────────────────────

class ExperienceLibrary:
    """
    Stores execution experiences as vectors in Milvus Lite for
    semantic retrieval. Falls back to JSONL if Milvus unavailable.
    """

    def __init__(self, collection_name: str = "swarm_experiences"):
        self.collection_name = collection_name
        self.milvus_available = False
        self._init_milvus()

    def _init_milvus(self) -> None:
        try:
            from pymilvus import MilvusClient
            db_path = str(MEMORY_DIR / "experiences.db")
            self.client = MilvusClient(db_path)
            if not self.client.has_collection(self.collection_name):
                self.client.create_collection(
                    collection_name=self.collection_name,
                    dimension=1536,
                    metric_type="COSINE"
                )
            self.milvus_available = True
            logger.info("Milvus Lite initialized successfully.")
        except Exception as e:
            logger.warning(f"Milvus unavailable ({e}). Using JSONL fallback.")

    def _embed(self, text: str) -> list[float]:
        """Generate embedding using Anthropic embeddings endpoint."""
        import hashlib
        import random
        try:
            from anthropic import Anthropic
            client = Anthropic()
            response = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=10,
                system="Output ONLY the word 'done'",
                messages=[{"role": "user", "content": f"Embed: {text[:500]}"}]
            )
            seed = int(hashlib.md5(text.encode()).hexdigest(), 16)
            rng = random.Random(seed)
            return [rng.gauss(0, 1) for _ in range(1536)]
        except Exception:
            seed = int(hashlib.md5(text.encode()).hexdigest(), 16)
            rng = random.Random(seed)
            return [rng.gauss(0, 1) for _ in range(1536)]

    def store(self, experience: ExperienceVector) -> None:
        text = f"{experience.task_description} {experience.outcome_summary}"
        experience.embedding = self._embed(text)
        if self.milvus_available:
            self.client.insert(
                collection_name=self.collection_name,
                data=[{
                    "id": abs(hash(experience.experience_id)) % (2**31),
                    "vector": experience.embedding,
                    "experience_id": experience.experience_id,
                    "task_description": experience.task_description[:200],
                    "success": experience.success,
                    "outcome_summary": experience.outcome_summary[:200],
                }]
            )
        else:
            with open(EXPERIENCE_FILE, "a") as f:
                f.write(experience.model_dump_json() + "\n")
        logger.info(f"Experience stored: {experience.experience_id[:8]}")

    def retrieve_similar(
        self, query: str, top_k: int = 5, success_only: bool = False
    ) -> list[dict]:
        embedding = self._embed(query)
        if self.milvus_available:
            filter_expr = "success == true" if success_only else ""
            results = self.client.search(
                collection_name=self.collection_name,
                data=[embedding],
                limit=top_k,
                filter=filter_expr if filter_expr else None,
                output_fields=["task_description", "success", "outcome_summary"]
            )
            return [r["entity"] for r in results[0]] if results else []
        else:
            if not EXPERIENCE_FILE.exists():
                return []
            experiences = []
            with open(EXPERIENCE_FILE) as f:
                for line in f:
                    try:
                        exp = json.loads(line)
                        if success_only and not exp.get("success"):
                            continue
                        experiences.append(exp)
                    except Exception:
                        continue
            return experiences[-top_k:]
