"""Skill Synthesis Engine — Test-Time Tool Evolution (HERMES Paradigm).

Implements on-demand Python skill generation, AST-level safety validation,
sandboxed execution, and permanent skill persistence using the SoK Taxonomy:
S = (C, pi, T, R) — Capability, Policy, Tests, Reward signal.

Part of the Swarm-Forge autonomous multi-agent orchestration framework.
"""
from __future__ import annotations

import ast
import asyncio
import importlib.util
import logging
import os
import textwrap
import time
from pathlib import Path
from typing import TYPE_CHECKING, Final

import anthropic

if TYPE_CHECKING:
    import types

    from .execution_sandbox import SandboxExecutor

logger: logging.Logger = logging.getLogger(__name__)

SKILLS_DIR: Final[str] = "swarm_skills"
MODEL_SYNTHESIS: Final[str] = "claude-sonnet-4-5"
MAX_SYNTHESIS_TOKENS: Final[int] = 2048
SYNTHESIS_SYSTEM_PROMPT: Final[str] = (
    "You are an expert Python 3.12 code synthesizer. "
    "Given a task objective, output ONLY valid Python 3.12 code "
    "followed by a separator line '# ---TESTS---' and then "
    "assert statements that verify the solution. "
    "Do not use markdown. Do not explain. Output raw Python only."
)
BLOCKED_AST_CALLS: Final[frozenset[str]] = frozenset({
    "os.system", "os.popen", "subprocess.Popen", "subprocess.call",
    "subprocess.run", "eval", "exec", "compile", "__import__",
})
ENV_API_KEY: Final[str] = "ANTHROPIC_API_KEY"


class SkillSynthesisEngine:
    """On-demand skill synthesizer implementing Test-Time Tool Evolution.

    Generates Python skills via the Anthropic API, validates them with an
    AST safety scan, exercises them in the shared :class:`SandboxExecutor`,
    and persists passing skills with a SoK Taxonomy docstring for later
    dynamic loading.

    Part of the Swarm-Forge autonomous multi-agent orchestration framework.
    """

    def __init__(
        self,
        sandbox: SandboxExecutor,
        skills_dir: str = SKILLS_DIR,
    ) -> None:
        """Initialize the engine.

        Args:
            sandbox: Existing SandboxExecutor instance for running generated code.
            skills_dir: Directory where synthesized skills are persisted.
        """
        self._sandbox: SandboxExecutor = sandbox
        self._skills_dir: Path = Path(skills_dir)
        self._skills_dir.mkdir(exist_ok=True)
        self._client: anthropic.Anthropic = anthropic.Anthropic(
            api_key=os.environ.get(ENV_API_KEY)
        )

    def _block_destructive_ast(self, code: str) -> tuple[bool, str]:
        """Parse code as AST and block any destructive OS/subprocess calls.

        Args:
            code: Python source code string to analyse.

        Returns:
            Tuple of (is_safe: bool, reason: str). If unsafe, reason names the
            blocked call.

        Raises:
            SyntaxError: If code is not valid Python.
        """
        tree = ast.parse(code)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                if isinstance(func, ast.Attribute):
                    full_name = f"{getattr(func.value, 'id', '')}.{func.attr}"
                    if full_name in BLOCKED_AST_CALLS:
                        return False, f"Blocked destructive call: {full_name}"
                elif isinstance(func, ast.Name):
                    if func.id in BLOCKED_AST_CALLS:
                        return False, f"Blocked destructive call: {func.id}"
        return True, ""

    def _format_skill_with_sok_taxonomy(
        self,
        skill_name: str,
        code: str,
        task_objective: str,
        test_assertions: str,
        passed: bool,
    ) -> str:
        """Wrap generated code in SoK Taxonomy docstring format.

        S = (C, pi, T, R): Capability, Policy, Tests, Reward.

        Args:
            skill_name: Snake_case identifier for the skill.
            code: The raw synthesized Python code.
            task_objective: Original task objective (C — Capability description).
            test_assertions: The test code that was run (T — Tests).
            passed: Whether the sandbox execution succeeded (R — Reward signal).

        Returns:
            Complete Python module string with SoK-formatted docstring.
        """
        reward = "1 (PASS)" if passed else "0 (FAIL)"
        indented_tests = textwrap.indent(test_assertions, "    ")
        header = textwrap.dedent(f"""\
            \"\"\"SoK Taxonomy — Synthesized Skill: {skill_name}

            S = (C, pi, T, R)
            C (Capability)  : {task_objective}
            pi (Policy)     : Generated by SkillSynthesisEngine via {MODEL_SYNTHESIS}
            T (Tests)       : See test_assertions below
            R (Reward)      : {reward}

            test_assertions:
            {indented_tests}
            \"\"\"
            """)
        return header + "\n" + code

    async def synthesize_on_demand(
        self,
        task_objective: str,
        node_id: str = "unknown",
    ) -> tuple[bool, str, str]:
        """Generate, validate, sandbox-test, and persist a new skill on demand.

        Implements Test-Time Tool Evolution (HERMES Paradigm):
            1. Call LLM to generate Python solution + test assertions.
            2. Run AST safety scan (block destructive OS/subprocess calls).
            3. Execute in existing SandboxExecutor.
            4. If tests pass, persist to ``swarm_skills/`` with SoK docstring.

        Args:
            task_objective: Natural-language description of the capability needed.
            node_id: DAG node ID requesting the synthesis (for logging).

        Returns:
            Tuple of (success: bool, skill_path: str, error_message: str).
            On success, skill_path is the absolute path to the saved .py file.
            On failure, skill_path is empty and error_message explains the reason.
        """
        logger.info(
            "SkillSynthesisEngine: synthesizing skill for node=%s objective=%r",
            node_id,
            task_objective[:80],
        )

        first_attempt = await self._attempt_synthesis(task_objective, prior_error="")
        if first_attempt.get("ok"):
            return True, first_attempt["skill_path"], ""

        # Single retry: feed the previous failure back to the model so it can
        # correct the concrete bug (syntax error, missing separator, unsafe
        # AST). Retry does NOT loop — one corrective attempt is enough.
        prior_error: str = first_attempt.get("error", "")
        logger.info(
            "SkillSynthesisEngine: retrying synthesis with error context: %s",
            prior_error[:120],
        )
        second_attempt = await self._attempt_synthesis(
            task_objective, prior_error=prior_error
        )
        if second_attempt.get("ok"):
            return True, second_attempt["skill_path"], ""
        return False, "", second_attempt.get("error", "synthesis failed")

    async def _attempt_synthesis(
        self,
        task_objective: str,
        prior_error: str,
    ) -> dict[str, str | bool]:
        """Run one synthesis attempt end-to-end.

        Args:
            task_objective: Capability description passed to the model.
            prior_error: Non-empty string on a retry attempt — contains the
                concrete failure mode from the prior attempt so the model
                can correct it. Empty string on the first attempt.

        Returns:
            ``{"ok": True, "skill_path": "<path>"}`` on success, or
            ``{"ok": False, "error": "<reason>"}`` on failure.
        """
        user_content: str = f"TASK OBJECTIVE:\n{task_objective}"
        if prior_error:
            user_content = (
                f"{user_content}\n\n"
                f"The previous attempt failed with: {prior_error}\n"
                "Generate a corrected version."
            )

        try:
            response = self._client.messages.create(
                model=MODEL_SYNTHESIS,
                max_tokens=MAX_SYNTHESIS_TOKENS,
                system=[{
                    "type": "text",
                    "text": SYNTHESIS_SYSTEM_PROMPT,
                    "cache_control": {"type": "ephemeral"},
                }],
                messages=[{"role": "user", "content": user_content}],
            )
            raw_output = response.content[0].text.strip()
        except anthropic.APIError as exc:
            logger.error("SkillSynthesisEngine: LLM call failed: %s", exc)
            return {"ok": False, "error": f"LLM synthesis failed: {exc}"}

        separator = "# ---TESTS---"
        if separator not in raw_output:
            return {
                "ok": False,
                "error": f"LLM did not include '{separator}' separator in output.",
            }
        code_part, _, test_part = raw_output.partition(separator)
        code_part = code_part.strip()
        test_part = test_part.strip()

        try:
            is_safe, reason = self._block_destructive_ast(code_part)
        except SyntaxError as exc:
            return {"ok": False, "error": f"Generated code has syntax error: {exc}"}
        if not is_safe:
            return {"ok": False, "error": f"AST safety violation: {reason}"}

        full_script = code_part + "\n\n" + test_part
        node_slug: str = f"retry_{int(time.time())}" if prior_error else f"{int(time.time())}"
        skill_name = f"skill_{node_slug}"
        tmp_path = self._skills_dir / f"{skill_name}_tmp.py"
        tmp_path.write_text(full_script, encoding="utf-8")

        result = await asyncio.to_thread(
            self._validate_script_syntax, str(tmp_path)
        )
        tmp_path.unlink(missing_ok=True)

        if not result.get("valid", False):
            return {
                "ok": False,
                "error": (
                    f"Sandbox syntax validation failed: "
                    f"{result.get('error', 'unknown')}"
                ),
            }

        final_code = self._format_skill_with_sok_taxonomy(
            skill_name=skill_name,
            code=code_part,
            task_objective=task_objective,
            test_assertions=test_part,
            passed=True,
        )
        skill_path = self._skills_dir / f"{skill_name}.py"
        skill_path.write_text(final_code, encoding="utf-8")
        logger.info("SkillSynthesisEngine: skill persisted at %s", skill_path)
        return {"ok": True, "skill_path": str(skill_path)}

    def _validate_script_syntax(self, script_path: str) -> dict[str, object]:
        """Compile a persisted script and return a validity verdict.

        Uses :func:`py_compile.compile` to surface syntax errors without
        executing the script, keeping synthesis cheap and side-effect free.

        Args:
            script_path: Absolute path to the candidate skill script.

        Returns:
            ``{"valid": bool, "error": str}`` describing compilation outcome.
        """
        import py_compile
        try:
            py_compile.compile(script_path, doraise=True)
            return {"valid": True, "error": ""}
        except py_compile.PyCompileError as exc:
            return {"valid": False, "error": str(exc)}
        except OSError as exc:
            return {"valid": False, "error": str(exc)}

    def load_skill(self, skill_path: str) -> types.ModuleType:
        """Dynamically load a persisted skill as a Python module.

        Args:
            skill_path: Absolute or relative path to the .py skill file.

        Returns:
            Loaded Python module object ready for use.

        Raises:
            ImportError: If the module cannot be loaded.
        """
        spec = importlib.util.spec_from_file_location("dynamic_skill", skill_path)
        if spec is None or spec.loader is None:
            raise ImportError(f"Cannot load skill from {skill_path}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
